[build]
  command = "hugo --minify"
  publish = "public"

[build.environment]
  HUGO_VERSION = "0.92.1"

[[headers]]
  for = "/*.(js|jpg|jpeg|gif|png|ico|cur|gz|svg|svgz|webp|mp3|mp4|ogg|ogv|webm|htc|css|ttf|ttc|otf|eot|woff|woff2)"
[headers.values]
  Cache-Control = "public, max-age=31536000, s-maxage=31536000, immutable" 

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    Content-Security-Policy = "object-src 'none';base-uri 'self';script-src 'nonce-oYrfS15m4xZCHSTxc4XeSg' 'strict-dynamic' 'report-sample' 'unsafe-eval' 'unsafe-inline' https: http:;"